name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          - dev
          - test
      deploy_docs:
        description: 'Build and deploy documentation?'
        required: false
        default: true
        type: boolean

jobs:
  build_and_package:
    strategy:
      matrix:
        node-version: [20]
    name: BUILD-JOB
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-slim

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show environment
        run:
          echo "Github actions are running"
          node --version
          npm --version

      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: echo "code is tested!"

      - name: Artifact Upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-${{ runner.os }}-node-${{ matrix.node-version }}
          path: |
            package*

      - name: Deploy
        run: echo "my code is deployed"

      - name: Rollback
        if: failure()
        run: echo "rollback is done"
